nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        host: '%env(HOSTNAME_URL)%'
        schemes: [http, https]
        info:
            title: Blog API
            description: This is an awesome app!
            version: 1.0.0
    areas:
        default:
            path_patterns: [ ^/api ]
