index:
    path: /
    controller: App\Controller\SiteController::index
    
app.swagger_ui:
    path: /api-doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api-doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
    
api_login_check:
    path:     /api/login
    methods:  POST

gesdinet_jwt_refresh_token:
    path:       /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
    methods:  POST

comment_new:
    path: /{_locale}/comment/{postSlug}/new
    controller: App\Controller\PostController::commentNew

facebook_login:
    path: /login/check-facebook

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login