index:
    path: /
    controller: App\Controller\SiteController::index
app.swagger_ui:
    path: /api-doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api-doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

api:
    path: /api
    controller: App\Controller\Api\SecurityController::api
api_login_check:
    path:     /api/login
    methods:  POST
