# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    router.request_context.host: '%env(HOSTNAME_URL)%'
    router.request_context.scheme: 'http'
    hostname_url: '%env(HOSTNAME_URL)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\DataFixtures\Faker\AppFaker:
        tags: [ { name: nelmio_alice.faker.provider } ]

    app.menu_builder:
        class: App\Menu\Builder
        arguments: ["@knp_menu.factory"]

    app.main_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", MainMenu]
        tags:
            - { name: knp_menu.menu, alias: nav }

    app.mobile_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", MobileMenu]
        tags:
            - { name: knp_menu.menu, alias: navMobile }

    app.footer_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", FooterMenu]
        tags:
            - { name: knp_menu.menu, alias: navFooter }

    app.sidebar_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", SidebarMenu]
        tags:
            - { name: knp_menu.menu, alias: navSidebar }

    app.tags_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", TagsMenu]
        tags:
            - { name: knp_menu.menu, alias: navTags }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extensions }


    my.oauth_aware.user_provider.service:
        class: App\Security\UserProvider
        arguments:
            - '@doctrine'
            - 'App\Entity\User'
            - {facebook: facebookID}

    App\Command\TestFixturesLoaderCommand:
        calls:
        - {method: setKernel, arguments: ['@kernel']}
        tags:
        - { name: console.command }